import Footer from '@/components/Footer'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: ' Next js  13',
  description: 'Generated by create next app goole clone',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen">{children}
      <Footer />

      
      </body>
    </html>
  )
}
