
import SearchHeader from '@/components/SearchHeader'
import { Inter } from 'next/font/google'
import './../globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: ' Next js  13',
  description: 'Generated by create next app goole clone',
}

export default function RootLayout({ children }) {
  return (
    <div>
        <SearchHeader />
        {children}
    </div>
  )
}
